name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    env:
      AUTHOR_TESTING: 1
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5' ]
        thread: [ 'true' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          multi-thread: ${{ matrix.thread }}
      - run: perl -V
      - name: install SWI-Prolog
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install swi-prolog
      - name: Install Perl deps
        run: |
          cpanm --verbose --notest --installdeps .
      - name: Install Perl author deps
        run: |
          cpanm --notest Test::Pod
      - name: Run tests
        run: |
          cpanm --verbose --test-only .
  ci-container:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    env:
      AUTHOR_TESTING: 1
    strategy:
      fail-fast: false
      matrix:
        perl: [ '5' ]
        thread: [ 'true' ]
        container:
          - swipl:7.5.15
          - swipl:7.6.4
          - swipl:7.7.25
          - swipl:8.0.3
          - swipl:8.1.0
          - swipl:8.1.15
          #- swipl:8.1.30
          #- swipl:8.2.4
          #- swipl:8.3.29
          #- swipl:8.4.0
          #- swipl:stable
    name: Perl ${{ matrix.perl }} with swipl container ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2
      - name: Get pre-reqs for steps
        run: |
          apt-get update && apt-get install -y build-essential xz-utils
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          multi-thread: ${{ matrix.thread }}
      - run: perl -V
      - name: Install Perl deps
        run: |
          cpanm --verbose --notest --installdeps .
      - name: Install Perl author deps
        run: |
          cpanm --notest Test::Pod
      - name: Run tests
        run: |
          cpanm --verbose --test-only .
