name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    env:
      AUTHOR_TESTING: 1
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5' ]
        thread: [ 'true' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          multi-thread: ${{ matrix.thread }}
      - run: perl -V
      - name: install SWI-Prolog
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install swi-prolog
      - name: Install Perl deps
        run: |
          cpanm --verbose --notest --installdeps .
      - name: Install Perl author deps
        run: |
          cpanm --notest Test::Pod
      - name: Run tests
        run: |
          cpanm --verbose --test-only .
